name: Automatic Updates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update and install packages
      run: sudo apt update && sudo apt install curl wget -y
    - name: Install sshx
      run: curl -sSf https://sshx.io/get | sh
    - name: sshx
      run: sshx
